// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "[DeviceID]";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onSpotsAvailableChange();
void onSpotMonitoringChange();
void onRedChange();
void onGreenChange();
void onBlueChange();

int spots_available;
bool spot_monitoring;
int red, green, blue;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(spots_available, READWRITE, ON_CHANGE, onSpotsAvailableChange);
  ArduinoCloud.addProperty(spot_monitoring, READWRITE, ON_CHANGE, onSpotMonitoringChange);
  ArduinoCloud.addProperty(red, READWRITE, ON_CHANGE, onRedChange);
  ArduinoCloud.addProperty(green, READWRITE, ON_CHANGE, onGreenChange);
  ArduinoCloud.addProperty(blue, READWRITE, ON_CHANGE, onBlueChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
